WIDTH = 50
HEIGHT = 50
ENERGY_SOURCE_POWER = 1.2
ENERGY_LOSS_RATE_MEAN = 0.9
ENERGY_LOSS_DEVIATION = 0.5
ENERGY_RANDOM_MIN = 0.1
ENERGY_MIN = 0.3
BIRTH_RATE = 0.3
INFINITY = 100000.

EPOCH = 30
TITLE_FORMAT = "Cells {} step(s) later"
SAVE_DIRECTORY_FORMAT = "./image/{}"
IMG_INTERPOLATION = "bilinear"
